### ISSUE TITLE
Executable output is not supported for this target

### ISSUE THREAD

**Issue by liudonghua123** [quickjs-zh/QuickJS#1]
I downloaded the `quickjs-windows-386-v20190709.zip` and extracted, Then I tried to build a executable for `hello_module.js` and `hello.js`. But none of them worked.

```
D:\apps\quickjs-windows-386\bin>qjsc -o hello_modulehello_module.js
SyntaxError: unsupported keyword: import
    at hello_module.js:3


D:\apps\quickjs-windows-386\bin>qjsc -o hello hello.js
Executable output is not supported for this target

```

**Comment by liudonghua123** [comment]
I also tried the linux version, the same errors.

![image](https://user-images.githubusercontent.com/2276718/61168794-e142de00-a585-11e9-8012-769fa693df37.png)

**Comment by llgoer** [comment]
Make sure QuickJS compiles and runs on 32-bit Windows and Linux systems.

**Comment by JokerQyou** [comment]
This is still an issue with the pre-built version (downloaded from 'release' section of this repository). I did not see any new release after your last comment. Why is this closed?

**Comment by liudonghua123** [comment]
Strange, the 64-bit System should be compatible with 32-bit applications.
