### ISSUE TITLE
QuickJS执行正则测试用例时报错：SyntaxError: too many captures

### ISSUE THREAD

**Issue by ty5491003** [quickjs-zh/QuickJS#13]
我在执行下面这个用例时：
![微信图片_20190727150455](https://user-images.githubusercontent.com/37855928/61991230-f2104b00-b07f-11e9-9849-8453d1e0384b.png)
QuickJS会报出错误：SyntaxError: too many captures
然而，我用其他引擎（V8/SpiderMonkey/chakra/javascriptCore等）执行同个用例，它们都能正确执行并返回索引值“0”。
所以我想知道，这个“捕获组数量限制”是QuickJS自己内部的规定，还是某个新的ECMAScript标准所要求的规范？

**Comment by llgoer** [comment]
libregexp.c可以将CAPTURE_COUNT_MAX 255设置更高

**Comment by ty5491003** [comment]
@llgoer 感谢回复。
