### ISSUE TITLE
MAC OS下./qjsc报错

### ISSUE THREAD

**Issue by goshawk-ym** [quickjs-zh/QuickJS#4]
./qjs examples/hello.js  已经正常跑通
但是运行./qjsc -o hello examples/hello.js报错如下：
no such file or directory: './libquickjs.bn.a'

**Comment by llgoer** [comment]
静态文件库在目录`/lib/quickjs`下，保证正确指向

**Comment by OliverLew** [comment]
@llgoer 小白问一下类似的问题，我用的Linux编译好的release版本，如果不将静态库文件放在系统目录下，如何配置环境变量？

我试过`LIBRARY_PATH`不知道对不对症，也没能解决问题。

目前报错是（貌似gcc在找一个特定的位置？）
```
$ ./bin/qjsc examples/hello.js -o hello
gcc: error: /root/quickjs-2019-07-09/dist/lib/quickjs/libquickjs.a: Permission denied
```
