### ISSUE TITLE
建议清理一下行尾空格

### ISSUE THREAD

**Issue by VimIcewind** [quickjs-zh/QuickJS#5]
不过需要注意里面有PDF文件不需要去行尾空格
`mv .git ..`
`find . -type f | xargs sed -i 's/\ \+$//g'`
`mv ../.git .`
`git reset HEAD -- *.pdf`
`git checkout *.pdf`
`git add .`
`git commit -m "Delete unused space of line end"`

**Comment by llgoer** [comment]
代码同官方保持一致，如果需要可以考虑建立分支
