### ISSUE TITLE
源代码在macOS Mojave version 10.14.5上无法编译

### ISSUE THREAD

**Issue by colinyuran** [quickjs-zh/QuickJS#6]
在QuickJS的官网上直接下载的7月9号的源代码，在mac上，make命令编译失败。然后搞了个ubuntu 18.04的虚拟机，make命令也失败。是我的环境有问题，还是怎么样。由人成功了么。

具体错误如下：
clang -m32 -g -flto -rdynamic -o qjs32 .obj/qjs.m32.o .obj/repl.m32.o .obj/quickjs.m32.o .obj/libregexp.m32.o .obj/libunicode.m32.o .obj/cutils.m32.o .obj/quickjs-libc.m32.o -lm -ldl
ld: warning: The i386 architecture is deprecated for macOS (remove from the Xcode build setting: ARCHS)
ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libm.tbd, missing required architecture i386 in file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libm.tbd
ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libdl.tbd, missing required architecture i386 in file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libdl.tbd
ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd, missing required architecture i386 in file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd
undef: ___stdinp
undef: ___stderrp
undef: ___stack_chk_guard
undef: _floor
undef: _sqrt
undef: _acos
undef: _asin
undef: _atan
undef: _atan2
undef: _ceil
undef: _cos
undef: _exp
undef: _tan
undef: _cosh
undef: _sinh
undef: _tanh
undef: ___vsnprintf_chk
undef: _pthread_mutex_unlock
undef: _memchr
undef: _asinh
undef: _atanh
undef: _putchar
undef: _expm1
undef: _cbrt
undef: _fclose
undef: _select$UNIX2003
undef: _signal
undef: _pthread_cond_wait$UNIX2003
undef: _rename
undef: _tcgetattr
undef: _strcpy
undef: _lseek
undef: _close$UNIX2003
undef: _pow
undef: _open$UNIX2003
undef: _printf
undef: _feof
undef: _clock$UNIX2003
undef: ___snprintf_chk
undef: _fflush
undef: _tmpfile
undef: _log
undef: _hypot
undef: _fputc
undef: ___moddi3
undef: _pthread_mutex_lock
undef: _strrchr
undef: _sin
undef: ___strcat_chk
undef: _pthread_cond_signal
undef: _malloc_size
undef: _pthread_cond_init$UNIX2003
undef: ___sprintf_chk
undef: _clock_gettime
undef: _putc
undef: ___divdi3
undef: _pthread_cond_timedwait$UNIX2003
undef: _strchr
undef: _fmod
undef: _free
undef: _lrint
undef: _pthread_cond_destroy
undef: _strlen
undef: _isatty
undef: _strtod$UNIX2003
undef: _localtime_r
undef: ___strcpy_chk
undef: _realloc
undef: _log2
undef: _dlsym
undef: _round
undef: _atoi
undef: _fesetround
undef: _fabs
undef: _fopen$UNIX2003
undef: _dlclose
undef: _ftell
undef: _acosh
undef: _fread
undef: _fputs$UNIX2003
undef: _trunc
undef: _fseek
undef: ___assert_rtn
undef: _fgetc
undef: _memmove
undef: _perror
undef: _memcmp
undef: _log1p
undef: _memset
undef: _read$UNIX2003
undef: _fprintf
undef: _exit
undef: _memset_pattern16
undef: _strerror$UNIX2003
undef: _tcsetattr
undef: _memcpy
undef: ___stdoutp
undef: _log10
undef: ___udivdi3
undef: _write$UNIX2003
undef: _strspn
undef: _dlopen
undef: _atexit
undef: ___stack_chk_fail
undef: ___bzero
undef: _malloc
undef: _strcmp
undef: _fwrite$UNIX2003
undef: _remove
undef: _fileno
undef: ___memcpy_chk
undef: _getenv
undef: ___error
undef: _abort
undef: _gettimeofday
undef: _ioctl
undef: _puts
Undefined symbols for architecture i386:
  "___stdinp", referenced from:
      _js_std_init in lto.o
  "___stderrp", referenced from:
      _main in lto.o
      _js_std_init in lto.o
  "___stack_chk_guard", referenced from:
      _JS_AddIntrinsicBaseObjects in lto.o
      _JS_AddIntrinsicMapSet in lto.o
      _JS_AddIntrinsicTypedArrays in lto.o
      _JS_NewAtomUInt32 in lto.o
      _JS_DumpMemoryUsage in lto.o
      _JS_ThrowSyntaxError in lto.o
      _JS_ThrowTypeError in lto.o
      ...
  "_floor", referenced from:
      _js_math_funcs in lto.o
  "_sqrt", referenced from:
      _js_math_funcs in lto.o
  "_acos", referenced from:
      _js_math_funcs in lto.o
  "_asin", referenced from:
      _js_math_funcs in lto.o
  "_atan", referenced from:
      _js_math_funcs in lto.o
  "_atan2", referenced from:
      _js_math_funcs in lto.o
  "_ceil", referenced from:
      _js_math_funcs in lto.o
  "_cos", referenced from:
      _js_math_funcs in lto.o
  "_exp", referenced from:
      _js_math_funcs in lto.o
  "_tan", referenced from:
      _js_math_funcs in lto.o
  "_cosh", referenced from:
      _js_math_funcs in lto.o
  "_sinh", referenced from:
      _js_math_funcs in lto.o
  "_tanh", referenced from:
      _js_math_funcs in lto.o
  "___vsnprintf_chk", referenced from:
      _JS_ThrowSyntaxError in lto.o
      _JS_ThrowTypeError in lto.o
      _JS_ThrowReferenceError in lto.o
      _JS_ThrowRangeError in lto.o
      _JS_ThrowInternalError in lto.o
      _js_parse_error in lto.o
      _js_parse_error1 in lto.o
      ...
  "_pthread_mutex_unlock", referenced from:
      _js_atomics_wait in lto.o
      _js_atomics_wake in lto.o
  "_memchr", referenced from:
      _js_typed_array_indexOf in lto.o
      _js_global_decodeURI in lto.o
      _js_global_encodeURI in lto.o
      _js_global_escape in lto.o
      _get_class_atom in lto.o
  "_asinh", referenced from:
      _js_math_funcs in lto.o
  "_atanh", referenced from:
      _js_math_funcs in lto.o
  "_putchar", referenced from:
      _js_std_dump_error in lto.o
      _js_print in lto.o
  "_expm1", referenced from:
      _js_math_funcs in lto.o
  "_cbrt", referenced from:
      _js_math_funcs in lto.o
  "_fclose", referenced from:
      _js_load_file in lto.o
      _js_std_file_close in lto.o
      _js_std_file_finalizer in lto.o
  "_select$UNIX2003", referenced from:
      _js_os_poll in lto.o
  "_signal", referenced from:
      _js_os_signal in lto.o
  "_pthread_cond_wait$UNIX2003", referenced from:
      _js_atomics_wait in lto.o
  "_rename", referenced from:
      _js_os_rename in lto.o
  "_tcgetattr", referenced from:
      _js_os_ttySetRaw in lto.o
  "_strcpy", referenced from:
      _js_module_loader in lto.o
  "_lseek", referenced from:
      _js_os_seek in lto.o
  "_close$UNIX2003", referenced from:
      _js_os_close in lto.o
  "_pow", referenced from:
      _js_atod in lto.o
      _js_binary_arith_slow in lto.o
      _js_pow in lto.o
  "_open$UNIX2003", referenced from:
      _js_os_open in lto.o
  "_printf", referenced from:
      _main in lto.o
      ___JS_FreeValueRT in lto.o
      _js_std_dump_error in lto.o
      _js_trace_malloc_printf in lto.o
     (maybe you meant: _dbuf_printf)
  "_feof", referenced from:
      _js_std_file_eof in lto.o
  "_clock$UNIX2003", referenced from:
      _main in lto.o
  "___snprintf_chk", referenced from:
      _JS_NewAtomUInt32 in lto.o
      _JS_SetPropertyInt64 in lto.o
      _JS_DeletePropertyInt64 in lto.o
      _JS_ToStringInternal in lto.o
      _JS_AtomGetStrRT in lto.o
      ___JS_AtomToValue in lto.o
      _js_dtoa in lto.o
      ...
  "_fflush", referenced from:
      _js_std_file_flush in lto.o
  "_tmpfile", referenced from:
      _js_std_tmpfile in lto.o
  "_log", referenced from:
      _js_math_funcs in lto.o
  "_hypot", referenced from:
      _js_math_hypot in lto.o
  "_fputc", referenced from:
      _js_std_file_putByte in lto.o
  "___moddi3", referenced from:
      _set_date_fields in lto.o
      _get_date_fields in lto.o
  "_pthread_mutex_lock", referenced from:
      _js_atomics_wait in lto.o
      _js_atomics_wake in lto.o
  "_strrchr", referenced from:
      _js_resolve_module in lto.o
  "_sin", referenced from:
      _js_math_funcs in lto.o
  "___strcat_chk", referenced from:
      _js_resolve_module in lto.o
  "_pthread_cond_signal", referenced from:
      _js_atomics_wake in lto.o
  "_malloc_size", referenced from:
      _js_trace_malloc in lto.o
      _js_trace_free in lto.o
      _js_trace_realloc in lto.o
      _js_trace_malloc_printf in lto.o
      _js_def_malloc in lto.o
      _js_def_free in lto.o
      _js_def_realloc in lto.o
      ...
  "_pthread_cond_init$UNIX2003", referenced from:
      _js_atomics_wait in lto.o
  "___sprintf_chk", referenced from:
      _js_dtoa in lto.o
  "_clock_gettime", referenced from:
      _js_atomics_wait in lto.o
      _js_os_setTimeout in lto.o
      _js_os_poll in lto.o
  "_putc", referenced from:
      _js_trace_malloc_printf in lto.o
     (maybe you meant: _dbuf_putc)
  "___divdi3", referenced from:
      _js_atomics_wait in lto.o
      _set_date_fields in lto.o
      _get_date_fields in lto.o
      _js_date_getTimezoneOffset in lto.o
  "_pthread_cond_timedwait$UNIX2003", referenced from:
      _js_atomics_wait in lto.o
  "_strchr", referenced from:
      _JS_AddIntrinsicBaseObjects in lto.o
      _unicode_script in lto.o
      _unicode_general_category in lto.o
      _unicode_prop in lto.o
      _js_module_loader in lto.o
  "_fmod", referenced from:
      _js_binary_arith_slow in lto.o
  "_free", referenced from:
      _main in lto.o
      _js_trace_free in lto.o
      _js_trace_realloc in lto.o
      _js_def_free in lto.o
      _js_def_realloc in lto.o
     (maybe you meant: _dbuf_free, _js_free , _cr_free , _js_std_free_handlers , _js_free_rt )
  "_lrint", referenced from:
      _JS_SetPropertyValue in lto.o
      _js_typed_array_fill in lto.o
  "_pthread_cond_destroy", referenced from:
      _js_atomics_wait in lto.o
  "_strlen", referenced from:
      _main in lto.o
      _js_strdup in lto.o
      _JS_NewRuntime2 in lto.o
      _JS_NewContextRaw in lto.o
      _JS_AddIntrinsicBaseObjects in lto.o
      _JS_AddIntrinsicTypedArrays in lto.o
      _JS_NewAtom in lto.o
      ...
  "_isatty", referenced from:
      _js_os_isatty in lto.o
  "_strtod$UNIX2003", referenced from:
      _js_dtoa in lto.o
      _js_atod in lto.o
  "_localtime_r", referenced from:
      _set_date_fields in lto.o
      _get_date_fields in lto.o
      _js_date_getTimezoneOffset in lto.o
  "___strcpy_chk", referenced from:
      _js_dtoa in lto.o
  "_realloc", referenced from:
      _js_trace_realloc in lto.o
      _js_def_realloc in lto.o
      _cr_default_realloc in lto.o
      _dbuf_default_realloc in lto.o
     (maybe you meant: _cr_realloc, _dbuf_realloc , _js_realloc2 , _js_realloc , _js_realloc_rt , _lre_realloc )
  "_log2", referenced from:
      _js_math_funcs in lto.o
  "_dlsym", referenced from:
      _js_module_loader in lto.o
  "_round", referenced from:
      _JS_ComputeMemoryUsage in lto.o
  "_atoi", referenced from:
      _js_dtoa in lto.o
  "_fesetround", referenced from:
      _js_dtoa in lto.o
  "_fabs", referenced from:
      _js_math_funcs in lto.o
  "_fopen$UNIX2003", referenced from:
      _js_load_file in lto.o
      _js_std_open in lto.o
  "_dlclose", referenced from:
      _js_module_loader in lto.o
  "_ftell", referenced from:
      _js_load_file in lto.o
      _js_std_file_tell in lto.o
  "_acosh", referenced from:
      _js_math_funcs in lto.o
  "_fread", referenced from:
      _js_load_file in lto.o
      _js_std_file_read_write in lto.o
  "_fputs$UNIX2003", referenced from:
      _js_std_dump_error in lto.o
      _js_std_file_puts in lto.o
      _js_print in lto.o
  "_trunc", referenced from:
      _js_math_funcs in lto.o
  "_fseek", referenced from:
      _js_load_file in lto.o
      _js_std_file_seek in lto.o
  "___assert_rtn", referenced from:
      _JS_FreeRuntime in lto.o
      _JS_RunGC in lto.o
      _JS_NewContextRaw in lto.o
      _JS_AddIntrinsicBaseObjects in lto.o
      _JS_SetClassProto in lto.o
      _JS_GetClassProto in lto.o
      _JS_NewStringLen in lto.o
      ...
  "_fgetc", referenced from:
      _js_std_file_getline in lto.o
      _js_std_file_readAsString in lto.o
      _js_std_file_getByte in lto.o
  "_memmove", referenced from:
      _JS_WriteObject in lto.o
      _cr_invert in lto.o
      _js_typed_array_set in lto.o
      _js_typed_array_copyWithin in lto.o
      _js_array_pop in lto.o
      _resolve_labels in lto.o
      _re_parse_disjunction in lto.o
      ...
  "_perror", referenced from:
      _main in lto.o
  "_memcmp", referenced from:
      _JS_NewAtomLen in lto.o
      _JS_NewClass in lto.o
      _unicode_script in lto.o
      _unicode_general_category in lto.o
      _unicode_prop in lto.o
      _has_suffix in lto.o
      _JS_AtomIsNumericIndex1 in lto.o
      ...
  "_log1p", referenced from:
      _js_math_funcs in lto.o
  "_memset", referenced from:
      _js_dtoa in lto.o
      _js_typed_array_fill in lto.o
      _js_create_function in lto.o
      _resolve_scope_var in lto.o
      _js_parse_statement_or_decl in lto.o
      _js_parse_destructing_element in lto.o
  "_read$UNIX2003", referenced from:
      _js_os_read_write in lto.o
  "_fprintf", referenced from:
      _main in lto.o
      _JS_DumpMemoryUsage in lto.o
  "_exit", referenced from:
      _help in lto.o
      _main in lto.o
      _js_std_eval_binary in lto.o
      _js_std_exit in lto.o
  "_memset_pattern16", referenced from:
      _JS_NewContextRaw in lto.o
      _JS_CallInternal in lto.o
      _js_call_c_function in lto.o
      _JS_NewClass1 in lto.o
      _js_c_function_data_call in lto.o
      _async_func_init in lto.o
      _js_async_generator_resume_next in lto.o
      ...
  "_strerror$UNIX2003", referenced from:
      _js_std_open in lto.o
      _js_std_tmpfile in lto.o
      _js_std_file_puts in lto.o
      _js_std_error_constructor in lto.o
      _js_std_error_strerror in lto.o
      _js_std_file_close in lto.o
      _js_std_file_printf in lto.o
      ...
  "_tcsetattr", referenced from:
      _js_os_ttySetRaw in lto.o
      _term_exit in lto.o
  "_memcpy", referenced from:
      _js_strndup in lto.o
      _js_strdup in lto.o
      _JS_NewRuntime2 in lto.o
      _JS_NewStringLen in lto.o
      _JS_NewClass in lto.o
      _JS_WriteObject in lto.o
      _lre_compile in lto.o
      ...
  "___stdoutp", referenced from:
      _main in lto.o
      _js_std_dump_error in lto.o
      _js_trace_malloc_printf in lto.o
      _js_std_init in lto.o
      _js_std_file_puts in lto.o
      _js_std_printf in lto.o
      _js_print in lto.o
      ...
  "_log10", referenced from:
      _js_math_funcs in lto.o
  "___udivdi3", referenced from:
      _js_dtoa in lto.o
      _js_atod in lto.o
  "_write$UNIX2003", referenced from:
      _js_os_read_write in lto.o
  "_strspn", referenced from:
      _js_std_open in lto.o
  "_dlopen", referenced from:
      _js_module_loader in lto.o
  "_atexit", referenced from:
      _js_os_ttySetRaw in lto.o
  "___stack_chk_fail", referenced from:
      _JS_AddIntrinsicBaseObjects in lto.o
      _JS_AddIntrinsicMapSet in lto.o
      _JS_AddIntrinsicTypedArrays in lto.o
      _JS_NewAtomUInt32 in lto.o
      _JS_DumpMemoryUsage in lto.o
      _JS_ThrowSyntaxError in lto.o
      _JS_ThrowTypeError in lto.o
      ...
  "___bzero", referenced from:
      _js_mallocz_rt in lto.o
      _js_mallocz in lto.o
      _JS_NewRuntime2 in lto.o
      _JS_NewContextRaw in lto.o
      _JS_ComputeMemoryUsage in lto.o
      _JS_ReadObject in lto.o
      _lre_exec in lto.o
      ...
  "_malloc", referenced from:
      _main in lto.o
      _js_load_file in lto.o
      _js_trace_malloc in lto.o
      _js_trace_realloc in lto.o
      _js_def_malloc in lto.o
      _js_def_realloc in lto.o
     (maybe you meant: _js_mallocz_rt, _js_mallocz , _js_malloc_rt , _js_malloc_usable_size_rt , _js_malloc , _js_malloc_usable_size )
  "_strcmp", referenced from:
      _main in lto.o
      _js_parse_directives in lto.o
      _re_parse_alternative in lto.o
      _get_class_atom in lto.o
  "_fwrite$UNIX2003", referenced from:
      _main in lto.o
      _JS_DumpMemoryUsage in lto.o
      _js_printf_internal in lto.o
      _js_std_file_read_write in lto.o
  "_remove", referenced from:
      _js_os_remove in lto.o
  "_fileno", referenced from:
      _js_std_file_fileno in lto.o
  "___memcpy_chk", referenced from:
      _js_dtoa in lto.o
  "_getenv", referenced from:
      _js_std_getenv in lto.o
  "___error", referenced from:
      _js_std_open in lto.o
      _js_std_tmpfile in lto.o
      _js_os_open in lto.o
      _js_os_close in lto.o
      _js_os_seek in lto.o
      _js_os_read_write in lto.o
      _js_os_remove in lto.o
      ...
  "_abort", referenced from:
      ___JS_FreeValueRT in lto.o
      _JS_DefineProperty in lto.o
      _JS_ToFloat64 in lto.o
      _JS_SetPropertyFunctionList in lto.o
      _JS_SetModuleExportList in lto.o
      _cr_op in lto.o
      _JS_CallInternal in lto.o
      ...
  "_gettimeofday", referenced from:
      _JS_AddIntrinsicBaseObjects in lto.o
      _js_date_constructor in lto.o
      _js_Date_now in lto.o
      _js___date_clock in lto.o
  "_ioctl", referenced from:
      _js_os_ttyGetWinSize in lto.o
  "_puts", referenced from:
      _help in lto.o
      _js_std_dump_error in lto.o
     (maybe you meant: _dbuf_putstr)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [qjs32] Error 1

**Comment by llgoer** [comment]
Like was mentioned, it appears Xcode for 10.14 doesn't support building 32-bit programs or libraries. You would need to downgrade Xcode to a version that supports 32-bit, and/or tell Apple you still need 32-bit support.

**Comment by hellllll0world** [comment]
You could build QuickJS on Mac by doing this

1. Comment ``CONFIG_M32=y``  on line 37 in makefile
2. Using the follow command to build instead of ``make`` 
```bash
make SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk MACOSX_DEPLOYMENT_TARGET=10.14

```
